package com.learn.easy;

/**
 * Created by Yinevg on 2019/8/5
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] helper = new int[26];
        for (int i = 0; i < s.length(); i++) {
            helper[s.charAt(i) - 'a']++;
        }
        for (int i = 0; i < t.length(); i++) {
            helper[t.charAt(i) - 'a']--;
        }
        int i = 0;
        for (; i < helper.length; i++) {
            if (helper[i] == -1) {
                break;
            }
        }
        return (char) ('a' + i);
    }
}
